### ISSUE TITLE
check files ingested in ChatApp index and delete specific ones

### ISSUE THREAD

**Issue by AstroWa3l** [mendableai/mendable-py#1]
Is there a way we could check/delete the index using the mendable API and then integrate that into the ChatApp? I did not see anything like that on the website documentation for the API.

**Comment by nickscamara** [comment]
Hey @AstroWa3l, not yet, but we are working on releasing that this week.

**Comment by AstroWa3l** [comment]
So cool, I cant wait thanks!!

**Comment by nickscamara** [comment]
hey @AstroWa3l, just opened the PR for it. It is also available in our docs/underlying API too here https://docs.mendable.ai/mendable-api/manage-data-sources
